[package]
name = "git-open"
version = "0.1.0"
authors = ["Kaustubh Patange <developerkp16@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-ini = "0.16"
webbrowser = "0.5.5"
